version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - formats: [binary]
    name_template: >-
      {{- .Binary -}}_{{- .Os -}}_{{- .Arch -}}
      {{- with .Arm -}}v{{ . }}{{- end -}}
      {{- with .Amd64 -}}{{ . }}{{- end -}}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
