name: ci

on:
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make test

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: check
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: build --single-target --snapshot --clean
